### ISSUE TITLE
Override default error message style

### ISSUE THREAD

**Issue by colinbruce** [ministryofjustice/govuk_elements_form_builder#46]
As a developer I'd like to override the default style of error messages.

I've been given plain english error messages by our content designer that cannot start with the model name.
<img width="525" alt="screen shot 2016-04-28 at 15 13 41" src="https://cloud.githubusercontent.com/assets/6757677/14888828/f5a568ea-0d53-11e6-991d-88d116cfd206.png">

Default rails style prefixes the model name to error message
<img width="607" alt="screen shot 2016-04-28 at 15 13 23" src="https://cloud.githubusercontent.com/assets/6757677/14888836/faf9efaa-0d53-11e6-846a-4605f7d8fee3.png">

Also, as the label still contains the model name, it seems superfluous, to me, but that might be my issue! ;)

Happy to open a PR and work on this if it's agreed that it could be useful.

**Comment by aliuk2012** [comment]
@colinbruce Have you tried using locales file to override it? 
https://govuk-elements-rails-guide.herokuapp.com/error-validation#form-error-validation

**Comment by colinbruce** [comment]
Looking at it now, but the guide doesn't give an example of overriding a specific models specific error.

**Comment by colinbruce** [comment]
Looking at [http://guides.rubyonrails.org/](http://guides.rubyonrails.org/i18n.html#translations-for-active-record-models)
```
errors.attributes.ni_number.blank
```
implies that
```
  errors:
    attributes:
      national_insurance:
        blank: 'Enter your National Insurance number'
        invalid: 'Enter a valid National Insurance number'
```
should work, but it's still returning standard blank response.

**Comment by colinbruce** [comment]
Using the following block
```
en:
  helpers:
    label:
      national_insurance:
        number: 'test National Insurance number'
  errors:
    messages:
      blank: 'is missing'
  activemodel:
    errors:
      models:
        forms/national_insurance:
          attributes:
            number:
              blank: 'Enter your National Insurance number'
              invalid: 'Enter a valid National Insurance number'
```
Overrides the default (can't be blank) and new(is missing) error messages but it is still appended to the model name
<img width="638" alt="screen shot 2016-04-28 at 16 40 12" src="https://cloud.githubusercontent.com/assets/6757677/14891760/ee02a48e-0d5f-11e6-8863-2feceef43a8f.png">

**Comment by robmckinnon** [comment]
[Active Model methods](http://guides.rubyonrails.org/i18n.html#active-model-methods) use [`errors.format`](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/locale/en.yml#L4) to format an error message.

The default errors format is `"%{attribute} %{message}"`.

You can **globally** change the errors format to `"%{message}"` like this:

```yml
en:
  errors:
    format: "%{message}"
    messages:
      blank: 'is missing'
activemodel:
    errors:
      models:
        forms/national_insurance:
          attributes:
            number:
              blank: 'Enter your National Insurance number'
```
Then you should see the error message as `Enter your National Insurance number`.

When you use this approach, you'll need to provide a custom message for all possible errors. Otherwise you risk users seeing an error message without an attribute name. For example, without a custom message users would see `is missing` instead of `National Insurance number is missing`.
