### ISSUE TITLE
radio_button_fieldset can't handle translations when there are errors

### ISSUE THREAD

**Issue by zheileman** [ministryofjustice/govuk_elements_form_builder#63]
There seem to be an issue handling the translations for radio buttons because when rendering the form it expects an array but when rendering the errors for the element it expects a string. Can't have both at the same time in the **en.yml** as one would overwrite the other.

Specific case I'm dealing with at the moment.
I have the following code (simplified a bit for this example):

```ruby
= GovukElementsErrorsHelper.error_summary @feedback, 'There are errors', 'Check below for more detail'

= form_for @feedback
   = f.radio_button_fieldset :rating, inline: true, choices: [5, 4, 3, 2, 1]
```

And in the **en.yml** file I have the following:

```yml
en:
  helpers:
    fieldset:
      feedback:
        rating: Overall, how satisfied were you with this service?
    hint:
      feedback:
        rating: Select from these options
    label:
      feedback:
        rating:
          '1': Very dissatisfied
          '2': Dissatisfied
          '3': Neither satisfied nor dissatisfied
          '4': Satisfied
          '5': Very satisfied
```

Overall it will produce the following expected result:

<img width="473" alt="screen shot 2016-10-14 at 16 00 13" src="https://cloud.githubusercontent.com/assets/687910/19392122/5695507c-9227-11e6-97a6-94127513f79b.png">

The problem comes when there are errors in the 'rating' field. It will produce the following with the above en.yml values because the 'rating' element is an array:

<img width="481" alt="screen shot 2016-10-14 at 16 01 24" src="https://cloud.githubusercontent.com/assets/687910/19392159/7b0911c8-9227-11e6-806a-4ec476c90a9d.png">

If I change in en.yml the array to be, as the documentation says, a string, said 'Rating' it will produce the following effect (the error will be correct, but the radio labels are gone):

```yml
en:
  helpers:
    label:
      feedback:
        rating: Rating
```
<img width="477" alt="screen shot 2016-10-14 at 16 03 27" src="https://cloud.githubusercontent.com/assets/687910/19392226/c44360fa-9227-11e6-9a29-0dcc4c163cbf.png">

Is there something I'm missing here, or is this bug? I'm not sure how to workaround this.

Thanks.
